name: flutter_imap_client
description: A simple IMAP client for Dart and Flutter.
version: 1.0.0
repository: https://github.com/FilibertoNencioni/flutter_imap_client

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
